server:
  port: 12377

spring:
  datasource:
    url: jdbc:mysql://175.178.117.153:3306/playfun?characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: playfun
    password: 3Giby7BL4E2AhbxH
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-viwe: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect